name: HA Linters

on:
  workflow_call:
    inputs:
      addon_path:
        required: true
        type: string

jobs:
  lint-addon:
    name: Lint Add-on
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v3
      - name: ğŸš€ Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2.11
        with:
          path: "./${{ inputs.addon_path }}"

  lint-hadolint:
    name: Hadolint
    needs:
      - information
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v3
      - name: ğŸš€ Run Hadolint
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: "./${{ inputs.addon_path }}/Dockerfile"

